# Configuration file for MegaLinter
# See all available variables at https://megalinter.io/latest/config-file/ and in linters documentation

# Allow all linters to autofix
APPLY_FIXES: all

# General MegaLinter parameters
PARALLEL: true
SARIF_REPORTER: true
FILEIO_REPORTER: true
SHOW_ELAPSED_TIME: true
GITHUB_STATUS_REPORTER: true
GITHUB_COMMENT_REPORTER: true

# Linter specific parameters
JSON_PRETTIER_ARGUMENTS: "--print-width 120"
YAML_PRETTIER_ARGUMENTS: "--print-width 120"
MARKDOWN_MARKDOWN_LINK_CHECK_ARGUMENTS: "--quiet"
REPOSITORY_GITLEAKS_CONFIG_FILE: ".github/linters/gitleaks.toml"
MARKDOWN_MARKDOWNLINT_FILTER_REGEX_EXCLUDE: (usage.md)

# Directories to ignore when linting
EXCLUDED_DIRECTORIES:
  - ".git"
  - "assets"
  - ".github"
  - ".devcontainer"

# Make errors for these linters show as warnings
DISABLE_ERRORS_LINTERS:
  - BASH_SHELLCHECK
  - MARKDOWN_MARKDOWN_LINK_CHECK
  - EDITORCONFIG_EDITORCONFIG_CHECKER

# Use these linters
ENABLE_LINTERS:
  - BASH_EXEC
  - BASH_SHFMT
  - BASH_SHELLCHECK
  - EDITORCONFIG_EDITORCONFIG_CHECKER
  - JSON_PRETTIER
  - JSON_JSONLINT
  - JSON_ESLINT_PLUGIN_JSONC
  - MARKDOWN_MARKDOWNLINT
  - MARKDOWN_MARKDOWN_LINK_CHECK
  - MARKDOWN_MARKDOWN_TABLE_FORMATTER
  - PYTHON_RUFF
  - REPOSITORY_GITLEAKS
  - REPOSITORY_GIT_DIFF
  - REPOSITORY_SECRETLINT
  - SPELL_MISSPELL
  - YAML_PRETTIER
