name: nf-core CI
# This workflow runs the pipeline with the minimal test dataset to check that it completes without any syntax errors
on:
  push:
    branches:
      - dev
  pull_request:
  workflow_dispatch:
  release:
    types: [published]

env:
  NXF_ANSI_LOG: false

concurrency:
  group: "${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}"
  cancel-in-progress: true

jobs:
  test:
    name: Run pipeline with test data
    # Only run on push if this is the nf-core dev branch (merged PRs)
    if: "${{ github.event_name != 'push' || (github.event_name == 'push' && github.repository == 'gregorysprenger/wf-paired-end-illumina-assembly') }}"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        NXF_VER:
          - "22.04.3"
          - "latest-everything"
    steps:
      - name: Free some space
        run: |
          sudo rm -rf "/usr/local/share/boost"
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"

      - name: Check out pipeline code
        uses: actions/checkout@v3

      - name: Install Nextflow
        uses: nf-core/setup-nextflow@v1
        with:
          version: "${{ matrix.NXF_VER }}"

      - name: Run pipeline with test data
        run: |
          nextflow run ${GITHUB_WORKSPACE} -profile test,docker --outdir ./results

  assemblers:
    name: Run workflow assemblers
    # Only run on push if this is the nf-core dev branch (merged PRs)
    if: ${{ github.event_name != 'push' || (github.event_name == 'push' && github.repository == 'gregorysprenger/wf-paired-end-illumina-assembly') }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Run remaining assemblers on test profile
        assembler: [skesa]

        NXF_VER:
          - "latest-everything"

    steps:
      - name: Free some space
        run: |
          sudo rm -rf "/usr/local/share/boost"
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"

      - name: Check out pipeline code
        uses: actions/checkout@v3

      - name: Install Nextflow
        uses: nf-core/setup-nextflow@v1
        with:
          version: "${{ matrix.NXF_VER }}"

      - name: Run pipeline with test data using ${{ matrix.assembler }} assembler
        run: |
          nextflow run ${GITHUB_WORKSPACE} -profile test,docker --outdir ./results --assembler ${{ matrix.assembler }}
