name: Release CI
# This workflow runs the pipeline with the full test dataset to check that it completes without any syntax errors
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
  release:
    types: [published]

env:
  NXF_ANSI_LOG: false

concurrency:
  group: "${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}"
  cancel-in-progress: true

jobs:
  test:
    name: Run pipeline with full test data
    # Only run on push if this is the nf-core dev branch (merged PRs)
    if: "${{ github.event_name != 'push' || (github.event_name == 'push' && github.repository == 'bacterial-genomics/wf-paired-end-illumina-assembly') }}"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        NXF_VER:
          - "latest-everything"
    steps:
      - name: Free some space
        run: |
          sudo rm -rf "/usr/local/share/boost"
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"

      - name: Check out pipeline code
        uses: actions/checkout@v3

      - name: Install Nextflow
        uses: nf-core/setup-nextflow@v1
        with:
          version: "${{ matrix.NXF_VER }}"

      - name: Run pipeline with full test data
        run: |
          nextflow run ${GITHUB_WORKSPACE} -profile test_full_skip_kraken,docker --outdir ./results
